# Generated by Django 3.2.4 on 2021-07-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_smalbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='smalbody',
            field=models.CharField(max_length=400),
        ),
    ]
