# Generated by Django 3.2.4 on 2021-07-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_smalbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='smalbody',
        ),
    ]
